//Essa funcao vai inicializar os valores do processo com zero, com excessao aos valores de $sa e $gp que sao o segmneto de memoria que o programa ira utilizar, entao recebera: endereco base dos registradores do processo, valor para $gp, valor para $sa
.initializeprocessmemory
LOAD $t0 $sa 1
LOAD $t1 $sa 2
LOAD $t2 $sa 3
ADDI $sa $sa 3
STORE $t0 $zero 0
STORE $t0 $zero 1
STORE $t0 $zero 2
STORE $t0 $zero 3
STORE $t0 $zero 4
STORE $t0 $zero 5
STORE $t0 $zero 6
STORE $t0 $zero 7
STORE $t0 $zero 8
STORE $t0 $zero 9
STORE $t0 $zero 10
STORE $t0 $zero 11
STORE $t0 $zero 12
STORE $t0 $zero 13
STORE $t0 $zero 14
STORE $t0 $zero 15
STORE $t0 $zero 16
STORE $t0 $zero 17
STORE $t0 $zero 18
STORE $t0 $zero 19
STORE $t0 $zero 20
STORE $t0 $zero 21
STORE $t0 $zero 22
STORE $t0 $zero 23
STORE $t0 $t1 24
STORE $t0 $t2 25
STORE $t0 $zero 26
STORE $t0 $zero 27
STORE $t0 $zero 28
STORE $t0 $zero 29